# Generated by Django 4.2.7 on 2023-12-01 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Super', 'Super'), ('Hyper', 'Hyper'), ('Sport', 'Sport')], max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('color', models.CharField(choices=[('-', '-'), ('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue')], max_length=50, null=True)),
                ('image', models.ImageField(default='Car.jpg', upload_to='cars_images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('-', '-'), ('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue')], max_length=50, null=True)),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.product')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
